name: Docker build ARM64 on tag
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  TAG_FMT: "^refs/tags/(((.?[0-9]+){3,4}))$"
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v3.3.5)'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build-arm64:
    runs-on: [self-hosted, linux, ARM64]
    timeout-minutes: 60
    name: Build and push arm64 image (native)
    steps:
      # Workaround based on JonasAlfredsson/docker-on-tmpfs@v1.0.1
      - name: Replace the current swap file
        shell: bash
        run: |
          if [ -f /mnt/swapfile ]; then
            sudo swapoff /mnt/swapfile
            sudo rm -v /mnt/swapfile
          fi
          sudo fallocate -l 13G /mnt/swapfile
          sudo chmod 600 /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile

      - name: Show current memory and swap status
        shell: bash
        run: |
          sudo free -h
          echo
          sudo swapon --show

      - name: Mount a tmpfs over /var/lib/docker
        shell: bash
        run: |
          if [ ! -d "/var/lib/docker" ]; then
            echo "Directory '/var/lib/docker' not found"
            exit 1
          fi
          sudo mount -t tmpfs -o size=10G tmpfs /var/lib/docker
          sudo systemctl restart docker
          sudo df -h | grep docker

      - name: Set env variables
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          fi

      - name: Show set environment variables
        run: |
          printf "      TAG: %s\n"  "$TAG"

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache-arm64
          key: ${{ runner.os }}-buildx-arm64
          restore-keys: |
            ${{ runner.os }}-buildx-arm64

      - name: Run Docker buildx for arm64
        run: |
          docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache-arm64" \
          --cache-to "type=local,dest=/tmp/.buildx-cache-arm64" \
          --platform linux/arm64 \
          --tag ghcr.io/opcat-labs/electrs:$TAG-arm64 \
          --tag ghcr.io/opcat-labs/electrs:latest-arm64 \
          --output "type=registry" . \
          --build-arg commitHash=$SHORT_SHA
